version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - go
    groups:
      kubernetes:
        patterns:
          - "k8s.io/*"
      charmbracelet:
        patterns:
          - "github.com/charmbracelet/*"
      golang-x:
        patterns:
          - "golang.org/x/*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - docker
